### ISSUE TITLE
Missing black box implementations

### ISSUE THREAD

**Issue by ucbjrl** [freechipsproject/treadle#56]
[dsptools BlackBoxFloatSpec tests](https://github.com/ucb-bar/dsptools/blob/master/src/test/scala/dsptools/numbers/BlackBoxFloat.scala) are failing with:
```bash
WARNING: external module "BBFAdd"(BBFAdd:BBFAdd)was not matched with an implementation
```
The WARNING isn't causing the failure, but I suspect the lack of an implementation for the black box interferes with the expected results.

These failures go away if `firrtl` or `verilator` backends are explicitly selected.

**Comment by chick** [comment]
Fixed some time ago
