### ISSUE TITLE
Add RPC interface to treadle

### ISSUE THREAD

**Issue by ekiwi** [freechipsproject/treadle#61]
This is a low priority feature request.

Essentially, the idea is to add an RPC interface to treadle that offers functionality similar to the repl.
This can then be used in order to compile and simulate FIRRTL from command line scripts with low latency (i.e. you do not have to pay the treadle startup cost every time you run your script).

I have a prototype implementation of this that uses a Python script to that communicates with the `treadle` repl via pipes and then exposes the functionality I needed via TCP.
The current interface is:
* **load** a firrtl file
* **peek** a signal
* **poke** a signal
* **step** n cycles

You can find my hacky prototype here: https://github.com/ekiwi/pyfirrtl/tree/treadle-server
To try it out, edit [simulator.py:106](https://github.com/ekiwi/pyfirrtl/blob/4a68f9d9bc2cbe1d8c55895dfddaf67385d2f2a1/simulator.py#L106) to adjust the `treadle_path`.
Then you can launch `./simulator.py`, wait until treade has been started and then run `./rtl.py` which will simulate a simple delayed inverter.

A nicer implementation would integrate this functionality directly into `treadle`, maybe using `gRPC`.
I would be happy to help with the implementation and testing, but I would be interested in hearing about other use-cases and the pros + cons of different RPC mechanisms first.

Are there any other people interested in this use case of `treadle` as a FIRRTL compilation and simulation server? What kind of RPC mechanism would be easiest to implement and maintain?

**Comment by chick** [comment]
This sounds like a good idea, I've put it on my todo list, not too deep, and it may have relevance to the chisel-gui project that we are working on.
