### ISSUE TITLE
Verilator and firrtl simulation gives very different results in the .vcd trace

### ISSUE THREAD

**Issue by oharboe** [freechipsproject/treadle#75]
Is there a reason why I should get different results in firrtl and Verilator?

I have been developing/testing with Verilator so far and my code works reasonably well. When I tried to write a unit-test with firrtl, the same test that passed in Verilator failed in firrtl.

Notice in the firrtl trace:

- The width of the reset signal for the sub-module is half the width of that of the parent module
- Signals in firrtl default to undefined. I guess this is intentional?
- The sub.io.enable signal goes to 0 half a clock *before* io.enable goes to 0 in the parent module

firrtl vcd file:

![image](https://user-images.githubusercontent.com/2798822/27389573-078cc39c-569f-11e7-8c6e-c63f1375ea1e.png)

Verilator vcd file:

![image](https://user-images.githubusercontent.com/2798822/27397612-40bf770a-56b7-11e7-860d-1f994ee861fa.png)

[vcdfiles.zip](https://github.com/freechipsproject/chisel3/files/1091774/vcdfiles.zip)

**Comment by chick** [comment]
Closing. Re-open if necessary
